---
title: "p8105_hw6_yl4358"
author: "YI LIU"
date: "11/21/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
library(mgcv)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}
birthweight_df = 
  read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("male", "female"), ordered = TRUE),
    frace = factor(frace, levels = c(1,2,3,4,8,9), labels = c("white", "black","asian","puerto_rican","other","unknown"), ordered = TRUE),
    malform = factor(malform, levels = c(0,1), labels = c("absent", "present"), ordered = TRUE),
    mrace = factor(mrace, levels = c(1,2,3,4,9), labels = c("white", "black","asian","puerto_rican","other"), ordered = TRUE)
  ) %>% 
  drop_na()
```

